### ISSUE TITLE
Documentation: Process to change external_location by environment

### ISSUE THREAD

**Issue by VDFaller** [Tomme/dbt-athena#107]
## Problem
I'm not understanding the accepted way to make `external_location` dynamic from dev to production.  

I unfortunately can't use the `s3_staging_dir` from `profiles.yml` because of a constraint of my IT.  Also the standard `{s3_staging_dir}/tables/uuid` doesn't make it easy to know which data goes with which table while looking through s3.  

## Pipe dream
I'd love it if I could have the `external_location` in the form of 

`s3://my-bucket/some_extra_path/tbl_schema/tbl_name`  

Where I give the external_location prefix (different one for dev, qa, prod) and the file would know what table schema it is going to and what the table name is without me having to configure it.

**Comment by ojaved-equip** [comment]
The tables not getting cleaned up was resolved by #73 

For making external_location dynamic in environments I specify a different staging directory for dev vs. prod and use the target.s3_staging_dir variable when setting the external location.

{{ config(materialized='table', external_location=target.s3_staging_dir+'_tables/[table name]') }}

**Comment by VDFaller** [comment]
I saw that one, but I updated to the latest version of DBT and it's still happening.  Has #73 not been released yet?

**Comment by ojaved-equip** [comment]
Did you update just DBT or dbt-athena plugin? I just updated the dbt-athena plugin and its working fine for me.

I'm not sure if there is a way to get around the different buckets but did see #50 still open which looks like what we really need.

**Comment by VDFaller** [comment]
Just double checked and upgraded again and it's still giving me the issue.  And from the code change of #73 that looks like it only has to do with incremental tables.  Mine is not incremental.  Maybe that's the disconnect?  

and yeah #50 looks like what I'm looking for for dev env things.

**Comment by mrshu** [comment]
@VDFaller #73 has already been released (in the sense that it's in the `master` branch). That change now applies to all tables, not just the incremental ones.

**Comment by VDFaller** [comment]
@mrshu Well I'm still getting this issue. /shrug  I'll try `dbt-glue`

**Comment by VDFaller** [comment]
Okay so I think I found the problem.  [clean_up_table](https://github.com/Tomme/dbt-athena/blob/b641dad1df647a9d8c75bf44e48773ac1e7a08c8/dbt/adapters/athena/impl.py#L90) is using my default credentials, (which don't have permission to get table for this environment, not even remote related actually).  So it's failing.  And since the error code was `AccessDeniedException` it was failing blindly.  Cascading into something hard to debug.  

I changed my profile to use default and changed that to the credentials that actually matter for this and it's running fine.  With or without external location.

**Comment by Gatsby-Lee** [comment]
@VDFaller Thank you for sharing your research in the issue!!
I had the similar issue like sth failed blindly.
